---

version: "2.4"
services:

  basenet:
    container_name: bastion
    image: debian:10
    domainname: localtest.nspcc.ru
    hostname: bastion
    command: ["/bin/sleep", "infinity"]
    restart: always
    stop_signal: SIGKILL
    environment:
      - TZ=Europe/Moscow
    networks:
      internet:
        ipv4_address: ${IPV4_PREFIX}.10

networks:
  internet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_PREFIX}.0/24
