---
kind: pipeline
type: docker
name: testenv-images

steps:
- name: neogo
  image: docker:19.03.5
  volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  environment:
      PASSWORD:
          from_secret: docker_passwd
      NEOGO_REPO_PATH:  'https://github.com/nspcc-dev/neo-go.git'
      NEOGO_REPO_TAG:   'master-2.x'
      NEOGO_IMG_REPO:   'registry.nspcc.ru/docker-local/neo-go'
      NEOGO_DOCKER_TAG: ''
      NEOGO_REGISTRY_USER: 'admin'
  commands:
    - apk add --update git make
    - git clone $NEOGO_REPO_PATH neo-go && cd neo-go && git checkout $NEOGO_REPO_TAG
    - NEOGO_DOCKER_TAG="${NEOGO_DOCKER_TAG:-`make version`}"
    - docker build --no-cache -t $NEOGO_IMG_REPO:$NEOGO_DOCKER_TAG ./
    - docker login registry.nspcc.ru -u $NEOGO_REGISTRY_USER -p "$PASSWORD"
    - docker push $NEOGO_IMG_REPO:$NEOGO_DOCKER_TAG

# no triggers added in this pipeline for now, because the
# only trigger for it is the developer's will

# host volume mount requires a repository to be `trusted`
# in drone; this option enables in repository settings
# by admin user
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

