---

version: "2.4"
services:

  storage01:
    image: nspccdev/neofs-storage:${NODE_VERSION}
    container_name: s01.localtest.nspcc.ru
    healthcheck:
      test: ["CMD", "neofs-node", "-health"]
      timeout: 10s
      retries: 50
    networks:
      storage_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.71
    stop_signal: SIGKILL
    volumes: [ "./01.key:/01.key" ]
    env_file: [ ".env", ".storage.env" ]
    environment:
    - NEOFS_NODE_PRIVATE_KEY=/01.key
    - NEOFS_NODE_ADDRESS=s01.localtest.nspcc.ru:8080
    - NEOFS_NODE_LOCATION=NorthAmerica
    - NEOFS_NODE_COUNTRY=US
    - NEOFS_NODE_CITY=NewYork

  storage02:
    image: nspccdev/neofs-storage:${NODE_VERSION}
    container_name: s02.localtest.nspcc.ru
    healthcheck:
      test: ["CMD", "neofs-node", "-health"]
      timeout: 10s
      retries: 50
    networks:
      storage_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.72
    stop_signal: SIGKILL
    volumes: [ "./02.key:/02.key" ]
    env_file: [ ".env", ".storage.env" ]
    environment:
    - NEOFS_NODE_PRIVATE_KEY=/02.key
    - NEOFS_NODE_ADDRESS=s02.localtest.nspcc.ru:8080
    - NEOFS_NODE_LOCATION=Asia
    - NEOFS_NODE_COUNTRY=SG
    - NEOFS_NODE_CITY=Singapore

  storage03:
    image: nspccdev/neofs-storage:${NODE_VERSION}
    container_name: s03.localtest.nspcc.ru
    healthcheck:
      test: ["CMD", "neofs-node", "-health"]
      timeout: 10s
      retries: 50
    networks:
      storage_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.73
    stop_signal: SIGKILL
    volumes: [ "./03.key:/03.key" ]
    env_file: [ ".env", ".storage.env" ]
    environment:
    - NEOFS_NODE_PRIVATE_KEY=/03.key
    - NEOFS_NODE_ADDRESS=s03.localtest.nspcc.ru:8080
    - NEOFS_NODE_LOCATION=Europe
    - NEOFS_NODE_COUNTRY=DE
    - NEOFS_NODE_CITY=Frankfurt

  storage04:
    image: nspccdev/neofs-storage:${NODE_VERSION}
    container_name: s04.localtest.nspcc.ru
    healthcheck:
      test: ["CMD", "neofs-node", "-health"]
      timeout: 10s
      retries: 50
    networks:
      storage_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.74
    stop_signal: SIGKILL
    volumes: [ "./04.key:/04.key" ]
    env_file: [ ".env", ".storage.env" ]
    environment:
    - NEOFS_NODE_PRIVATE_KEY=/04.key
    - NEOFS_NODE_ADDRESS=s04.localtest.nspcc.ru:8080
    - NEOFS_NODE_LOCATION=Europe
    - NEOFS_NODE_COUNTRY=GB
    - NEOFS_NODE_CITY=London

  neofs-storage-healthy:
    image: alpine
    depends_on:
      storage01:
        condition: service_healthy
      storage02:
        condition: service_healthy
      storage03:
        condition: service_healthy
      storage04:
        condition: service_healthy

networks:
  storage_int:
  internet:
    external:
      name: basenet_internet
